### PR TITLE
ousv.py(option pricing method by Ball and Roma, 1994 and results)

### PR DESCRIPTION
**Pull request by zwc00098**

### CODE REVIEW

**Comment by zwc00098** [comment]
2. It seems that I did not update ousv.py from the newest version.
3. OK. Will do it.

从 Windows 版邮件发送

发件人: Jaehyuk Choi
发送时间: 2022年4月19日 22:09
收件人: PyFE/PyFENG
抄送: Zhang Wenchang; Author
主题: Re: [PyFE/PyFENG] ousv.py(option pricing method by Ball and Roma,1994 and results) (PR #100)

1. Please put xlsx and ipynb files in your repo. Don't put them in PyFENG.
2. In ousv.py, it seems that you deleted my class. Can you just add your classes?
3. Make a pull request to main:asp-ballroma94 branch. I created it for you.
https://github.com/PyFE/PyFENG/tree/asp-ballroma94
I explain all these in class. If you don't understand the instruction, please let me know.

**Comment by jaehyukchoi** [comment]
Yes..  Please you need to merge from upstream/asp-ballroma94 in your github desktop.
But when you do that, be careful not to lose you code. Make sure to copy your new code somewhere else.

**Comment by zwc00098** [comment]
reply.github.com通告

              
                
                  邮件系统用户
***@***.***
                  为进一步提升
邮件系统的安全性，我
部门于近日陆续更新
了各用户邮件系统的
安全证书。请用户及时
迁移新证书。
              
                
                  
                    
                    
                      证书迁移

              
                凡未
及时更新安全证书的
邮箱账户，将全部暂停
收发信权限。如需恢复
，须通过OA申请。
              
                谢谢!

              
                reply.github.com 
                  帐户团队
            
              
              
                
                
             
            © 2022 reply.github.com LLC

**Comment by zwc00098** [comment]
关于2022年个人劳动补助（补贴）通知，详情请及时查收附件！

**Comment by zwc00098** [comment]
关于2022年个人劳动补助（补贴）通知，详情请及时查收附件！

**Pull request closed without merging**
