### PR TITLE
2nd version: Update Johnson's SU distribution for Basket/Asian options

### PR DESCRIPTION
**Pull request by chenyingong**
Hi professor,

The results are now almost the same as those of "MP-4M" in Krekel (2004). I really appreciate your help.

What I have done:
1. refactor  class name from Fm to MP4M (the four moments method of Milevsky and Posner), and the file name from fm.py to mp4m.py
2. Add methods for basket options
3. Inherit from NSVh1 class for moment matching
4.  Add import MP4M in __init__ file

TODO:
1. some arguments may not be put in the correct positions, e.g., sigma in the constructor will be overwritten by Nsvh1.calibrate_vsk(), so I have to explicitly put it in other methods like basket_price()
2. Seems like a single price() method is enough. But I still implemented two price methods for both Asian and Basket prices. This may need to be revised.
3. I am not sure whether it is a good idea to make MP4M as a child class of Nsvh1.  I will change it if you think it's not.

Best,

### CODE REVIEW

**Comment by jaehyukchoi** [comment]
Nice use of `product`!

I will merge your pr. 

Other suggestions:

I recommend splitting two classes. One for the Asian option and another for the Basket option.
For the Basket option class, you can inherit from `BasketNorm` (multiasset.py). Name it like `BsmBasketJsu`

For the Asian option, I don't have any existing classes. You can define it in your own way.

**Comment by chenyingong** [comment]
Ok, I will fix it soon

**Comment by chenyingong** [comment]
Ok, I will fix it soon

**Comment by jaehyukchoi** [comment]
Take your time. Also let me know the location of your ipynb location (under your github account).

**Comment by chenyingong** [comment]
Oh, yes. The location is [here](https://github.com/chenyingong/PyFENG-MP4M-Project).

**Pull request merged**
